appName: recommendationservice
containerImage: gcr.io/google-samples/microservices-demo/recommendationservice
imageTag: v0.3.5
containerENV:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"
